#!/data/data/com.termux/files/usr/bin/bash
# This hook is run when the list of virtualenvs is printed so each name can include details.
# argument: environment name

if [ -e $1/.project ]; then
  cat $1/.project | cut -d"/" -f7-
else
  echo "[no project binded]"
fi

$WORKON_HOME/packages_count_for $1

du -sh $1 |
  sed -e "s/\([^ \t]\)[ \t]*$1$/\1/g" \
      -e "s/M$/ MB/g"
